//CREATE TABLE QUERY
CREATE TABLE STUDENT(SID INTEGER, SNAME VARCHAR(25),SADDRESS VARCHAR(25),SEMAILID VARCHAR(10),SGRADE VARCHAR(2),SMARKS INTEGER)

CREATE TABLE TEACHER(TID INTEGER,TNAME VARCHAR(25))

//INSERT DATA QUERY
INSERT INTO STUDENT VALUES(1,'MAX','ROCHESTER','MAX@RIT.EDU','A',100)
INSERT INTO STUDENT VALUES(2,'BILL','ROCHESTER','BILL@RIT.EDU','B',90)
INSERT INTO STUDENT VALUES(3,'WILL','ROCHESTER','WILL@RIT.EDU','B',95)

INSERT INTO TEACHER VALUES(1,'TOM')
INSERT INTO TEACHER VALUES(2,'SAM')
INSERT INTO TEACHER VALUES(3,'LINA')

//ALTER TABLE DROP COLUMN QUERY
ALTER TABLE STUDENT DROP COLUMN(SGRADE,SID)

//SELECT * QUERY
SELECT * FROM (STUDENT,TEACHER)


ENUM QUERIES
CREATE TABLE TEST(
ID INT PRIMARY KEY, NAME VARCHAR(255),
color Enum("pink", "green")
)

INSERT INTO TEST VALUES (100, ’SAMYUKTA’, ‘pink')
INSERT INTO TEST VALUES (150, ’RODE’, ‘green')
INSERT INTO TEST VALUES (200, ’AMRUTA’, ‘green')
INSERT INTO TEST VALUES (250, ’CHAVAN’, ‘green')
INSERT INTO TEST VALUES (300, ’SAURABH’, ‘pink')
INSERT INTO TEST VALUES (350, ’BHARADWAJ’, ‘pink')
INSERT INTO TEST VALUES (400, ’PURI’, ‘pink')


UPDATE TABLE TEST SET NAME = “BHARAT” WHERE ID = 100